define([], function() {
  return {
    "PropertyPaneDescription": "Choose how Priority Banner displays SharePoint messages",
    "DisplayGroupName": "Display",
    "LayoutFieldLabel": "Display format",
    "LayoutStandard": "Standard",
    "LayoutCompact": "Compact",
    "DismissLabel": "Dismiss this message",
    "PriorityInformation": "Information",
    "PriorityImportant": "Important",
    "PriorityUrgent": "Urgent",
    "PriorityCritical": "Critical",
    "ConfigurationTitle": "Set up Priority Messages",
    "ConfigurationDescription": "Create the standard SharePoint list used to manage messages on this site.",
    "CreateButton": "Create list",
    "CreatingTitle": "Creating the list",
    "CreatingDescription": "Priority Banner is preparing the columns and settings. Keep this page open.",
    "EmptyTitle": "No messages yet",
    "EmptyDescription": "The list is ready. Add your first priority message to display it here.",
    "OpenListButton": "Open the list",
    "IncompatibleTitle": "The list needs attention",
    "IncompatibleDescription": "The Priority Messages list exists but required columns are missing.",
    "PermissionTitle": "Permission required",
    "PermissionDescription": "A site owner must create or access the Priority Messages list.",
    "ErrorTitle": "Messages are temporarily unavailable",
    "ErrorDescription": "Priority Banner could not read its SharePoint list. Try again.",
    "RetryButton": "Try again",
    "LoadingTitle": "Loading priority messages",
    "LoadingDescription": "Priority Banner is checking the SharePoint list.",
    "ListDisplayTitle": "Priority Messages",
    "ListDescription": "Time-bound priority messages displayed on SharePoint pages."
  }
});
