define([], function() {
  return {
    "PropertyPaneDescription": "Configure this priority message directly on the page.",
    "ContentGroupName": "Content",
    "TitleFieldLabel": "Title",
    "MessageFieldLabel": "Message",
    "PriorityFieldLabel": "Priority",
    "ExpirationGroupName": "Expiration",
    "ExpirationFieldLabel": "Expiration date and time (optional)",
    "ExpirationFieldDescription": "Leave empty to keep the message visible indefinitely.",
    "ExpirationPastError": "The expiration must be later than the current date and time.",
    "ActionGroupName": "Action and dismissal",
    "ActionUrlFieldLabel": "Link (optional)",
    "ActionTextFieldLabel": "Button text (optional)",
    "AllowDismissFieldLabel": "Allow visitors to dismiss this message",
    "TranslationGroupName": "Optional translation",
    "EnableTranslationFieldLabel": "Add a translation",
    "TranslatedTitleFieldLabel": "Translated title",
    "TranslatedMessageFieldLabel": "Translated message",
    "TranslatedActionFieldLabel": "Translated button text (optional)",
    "EnglishLanguageLabel": "English",
    "FrenchLanguageLabel": "French",
    "DisplayGroupName": "Display",
    "LayoutFieldLabel": "Layout",
    "LayoutStandard": "Standard",
    "LayoutCompact": "Compact",
    "DismissLabel": "Dismiss this message",
    "DefaultActionText": "Learn more",
    "PriorityInformation": "Information",
    "PriorityImportant": "Important",
    "PriorityUrgent": "Urgent",
    "PriorityCritical": "Critical",
    "ConfigureTitle": "Configure this priority message",
    "ConfigureDescription": "Open the web part properties to enter a title and message.",
    "ExpiredTitle": "This priority message has expired",
    "ExpiredDescription": "Choose a future expiration date or clear the expiration to display it again.",
    "RequiredFieldError": "This field is required.",
    "TranslationPairError": "Provide both the translated title and translated message.",
    "InvalidUrlError": "Enter an HTTPS, HTTP, site-relative, or anchor link.",
    "YesLabel": "Yes",
    "NoLabel": "No"
  };
});
