define([], function() {
  return {
    "PropertyPaneDescription": "Choisissez comment Priority Banner affiche les messages SharePoint",
    "DisplayGroupName": "Affichage",
    "LayoutFieldLabel": "Format d’affichage",
    "LayoutStandard": "Standard",
    "LayoutCompact": "Compact",
    "DismissLabel": "Fermer ce message",
    "PriorityInformation": "Information",
    "PriorityImportant": "Important",
    "PriorityUrgent": "Urgent",
    "PriorityCritical": "Critique",
    "ConfigurationTitle": "Configurer les messages prioritaires",
    "ConfigurationDescription": "Créez la liste SharePoint standard utilisée pour gérer les messages de ce site.",
    "CreateButton": "Créer la liste",
    "CreatingTitle": "Création de la liste",
    "CreatingDescription": "Priority Banner prépare les colonnes et les paramètres. Gardez cette page ouverte.",
    "EmptyTitle": "Aucun message pour le moment",
    "EmptyDescription": "La liste est prête. Ajoutez votre premier message prioritaire pour l’afficher ici.",
    "OpenListButton": "Ouvrir la liste",
    "IncompatibleTitle": "La liste nécessite une intervention",
    "IncompatibleDescription": "La liste des messages prioritaires existe, mais des colonnes obligatoires sont absentes.",
    "PermissionTitle": "Autorisation requise",
    "PermissionDescription": "Un propriétaire du site doit créer ou ouvrir la liste des messages prioritaires.",
    "ErrorTitle": "Les messages sont temporairement indisponibles",
    "ErrorDescription": "Priority Banner ne peut pas lire sa liste SharePoint. Réessayez.",
    "RetryButton": "Réessayer",
    "LoadingTitle": "Chargement des messages prioritaires",
    "LoadingDescription": "Priority Banner vérifie la liste SharePoint.",
    "ListDisplayTitle": "Messages prioritaires",
    "ListDescription": "Messages prioritaires programmés affichés dans les pages SharePoint."
  }
});
