define([], function() {
  return {
    "PropertyPaneDescription": "Configurez ce message prioritaire directement dans la page.",
    "ContentGroupName": "Contenu",
    "TitleFieldLabel": "Titre",
    "MessageFieldLabel": "Message",
    "PriorityFieldLabel": "Priorité",
    "ExpirationGroupName": "Expiration",
    "ExpirationFieldLabel": "Date et heure d’expiration (facultatives)",
    "ExpirationFieldDescription": "Laissez vide pour afficher le message sans limite de temps.",
    "ExpirationPastError": "L’expiration doit être postérieure à la date et à l’heure actuelles.",
    "ActionGroupName": "Action et fermeture",
    "ActionUrlFieldLabel": "Lien (facultatif)",
    "ActionTextFieldLabel": "Texte du bouton (facultatif)",
    "AllowDismissFieldLabel": "Autoriser les visiteurs à fermer ce message",
    "TranslationGroupName": "Traduction facultative",
    "EnableTranslationFieldLabel": "Ajouter une traduction",
    "TranslatedTitleFieldLabel": "Titre traduit",
    "TranslatedMessageFieldLabel": "Message traduit",
    "TranslatedActionFieldLabel": "Texte traduit du bouton",
    "EnglishLanguageLabel": "Anglais",
    "FrenchLanguageLabel": "Français",
    "DisplayGroupName": "Affichage",
    "LayoutFieldLabel": "Format d’affichage",
    "LayoutStandard": "Standard",
    "LayoutCompact": "Compact",
    "DismissLabel": "Fermer ce message",
    "DefaultActionText": "En savoir plus",
    "PriorityInformation": "Information",
    "PriorityImportant": "Important",
    "PriorityUrgent": "Urgent",
    "PriorityCritical": "Critique",
    "ConfigureTitle": "Configurer ce message prioritaire",
    "ConfigureDescription": "Ouvrez le panneau de propriétés pour saisir le titre et le message.",
    "ExpiredTitle": "Ce message a expiré",
    "ExpiredDescription": "Choisissez une nouvelle date d’expiration ou retirez-la pour réafficher le message.",
    "RequiredFieldError": "Ce champ est obligatoire.",
    "TranslationPairError": "Le titre et le message traduits doivent être remplis ensemble.",
    "InvalidUrlError": "Utilisez une adresse HTTPS, HTTP ou un lien SharePoint relatif.",
    "YesLabel": "Oui",
    "NoLabel": "Non"
  };
});
